# Copyright 2023 The MathWorks, Inc.

ARG BASE_REGISTRY=redhat
ARG BASE_IMAGE=ubi8
ARG BASE_TAG=8.9
ARG IMAGE_UNDER_TEST=novnc

FROM ${IMAGE_UNDER_TEST} AS image-under-test

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

COPY --from=image-under-test *.tar.gz /tmp

RUN mkdir /tmp/novnc/ && \
    tar -xzf /tmp/novnc.tar.gz --directory /tmp/novnc/ --no-same-owner --no-same-permissions
