# Copyright 2023-2026 The MathWorks, Inc.

ARG BASE_IMAGE
ARG IMAGE_UNDER_TEST

FROM ${IMAGE_UNDER_TEST} AS image-under-test

FROM ${BASE_IMAGE}

COPY --from=image-under-test *.tar.gz /tmp

RUN mkdir /tmp/novnc/ && \
    tar -xzf /tmp/novnc.tar.gz --directory /tmp/novnc/ --no-same-owner --no-same-permissions
