# Copyright 2024-2025 The MathWorks, Inc.

MATLAB_RELEASE="R2024a"

MATLAB_DEPS_OS="ubuntu24.04"

GCC="gcc-12"
GPP="g++-12"

DEEP_LEARNING_SPKGS="Deep_Learning_Toolbox_Model_for_AlexNet_Network Deep_Learning_Toolbox_Model_for_GoogLeNet_Network Deep_Learning_Toolbox_Model_for_Inception-ResNet-v2_Network Deep_Learning_Toolbox_Model_for_Inception-v3_Network Deep_Learning_Toolbox_Model_for_ResNet-101_Network Deep_Learning_Toolbox_Model_for_ResNet-18_Network Deep_Learning_Toolbox_Model_for_ResNet-50_Network Deep_Learning_Toolbox_Verification_Library Deep_Learning_Toolbox_Importer_for_Caffe_Models Deep_Learning_Toolbox_Converter_for_TensorFlow_models GPU_Coder_Interface_for_Deep_Learning_Libraries MATLAB_Coder_Interface_for_Deep_Learning_Libraries Deep_Learning_Toolbox_Converter_for_ONNX_Model_Format"
