# Copyright 2025-2026 The MathWorks, Inc.

# This file builds, tests & publishes the mathworks/matlab-deps Docker Images to DockerHub.

name: Build, Test and Publish multiple MATLAB Dependencies images

on:
  workflow_dispatch:

  # Runs at 02:00 every Monday
  schedule:
    - cron: "0 2 * * 1"

  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-test-and-publish-matlab-deps.yml"
      - ".github/actions/build-test-and-publish-matlab-deps/action.yml"
      - "matlab-deps/**"
      - "tests/matlab-deps/**"

env:
  latest_release: r2026a
  releases: '[
    { "release": "r2019b", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2020a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2020b", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2021a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2021b", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2022a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2022b", "default_os": "ubuntu22.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2023a", "default_os": "ubuntu22.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2023b", "default_os": "ubuntu22.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2024a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2024b", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2025a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2025b", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04"], "platforms": "linux/amd64" },
    { "release": "r2026a", "default_os": "ubuntu24.04", "supported_os": ["aws-batch", "ubi8", "ubi9", "ubuntu22.04", "ubuntu24.04", "debian12", "debian13"], "platforms": "linux/amd64" }
    ]'

jobs:
  generate-inputs:
    runs-on: ubuntu-latest

    permissions: {}

    outputs:
      image_input_data: ${{ steps.gen-json-list.outputs.image_input_data }}
      latest_release: ${{ env.latest_release }}

    steps:
      - name: Generate JSON list of inputs to build and test images
        id: gen-json-list
        env:
          releases: ${{ env.releases }}
        # The script below takes the releases JSON as input and generates a (JSON-formatted) list of inputs for the build-test-and-publish job.
        # The input JSON has a list of supported OSes for each release, and the script generates an entry for each release-OS combination.
        # Each of the objects in the output JSON array contains:
        #   - release_tag: The MATLAB release version
        #   - os_info_tag: The operating system tag
        #   - default_os: The default operating system for the release
        #   - test_file_name: The name of the test file, derived from the os_info_tag
        #   - platforms: The set of platforms that the image will be built for
        #
        # The expected structure of the input JSON is:
        #  [
        #    {
        #      "release": "r2019b",
        #      "default_os": "ubuntu24.04",
        #      "supported_os": [
        #        "aws-batch",
        #        "ubuntu24.04"
        #      ]
        #    },
        #    ...
        #    {
        #      "release": "r2024b",
        #      "default_os": "ubuntu22.04",
        #      "supported_os": [
        #        "aws-batch",
        #        ...
        #        "ubuntu24.04"
        #      ]
        #    }
        #  ]
        #
        # The expected structure of the output JSON is:
        #  [
        #    {
        #      "release_tag": "r2019b",
        #      "os_info_tag": "aws-batch",
        #      "default_os": "ubuntu24.04",
        #      "platforms": "linux/amd64"
        #      "test_file_name": "test_awsbatch.py"
        #    },
        #    {
        #      "release_tag": "r2019b",
        #      "os_info_tag": "ubuntu24.04",
        #      "default_os": "ubuntu24.04",
        #      "platforms": "linux/amd64"
        #      "test_file_name": "test_ubuntu2404.py"
        #    },
        #    ...
        #    {
        #      "release_tag": "r2026a",
        #      "os_info_tag": "aws-batch",
        #      "default_os": "ubuntu24.04",
        #      "platforms": "linux/amd64,linux/arm64"
        #      "test_file_name": "test_awsbatch.py"
        #    },
        #    ...
        #    {
        #      "release_tag": "r2026a",
        #      "os_info_tag": "ubuntu24.04",
        #      "default_os": "ubuntu24.04",
        #      "platforms": "linux/amd64,linux/arm64"
        #      "test_file_name": "test_ubuntu2404.py"
        #    }
        #  ]
        #
        # \($os | gsub("-|\\.";"")) removes all hyphens (-) and dots (.) in $os. gsub is a jq function for global substitution.
        run: |
          list=$(echo ${releases} | jq -c '[.[] | .supported_os[] as $os | {
            release_tag: .release,
            os_info_tag: $os,
            default_os: .default_os,
            platforms: .platforms,
            test_file_name: "test_\($os | gsub("-|\\.";"")).py"
          }]')
          echo "image_input_data=$list" >> "$GITHUB_OUTPUT"

  build-test-push-all-images:
    needs: generate-inputs
    strategy:
      fail-fast: false
      matrix:
        image_input_data: ${{ fromJson(needs.generate-inputs.outputs.image_input_data) }}
    uses: ./.github/workflows/build-test-and-publish-single-matlab-deps.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      matlab_release_tag: ${{ matrix.image_input_data.release_tag }}
      os_info_tag: ${{ matrix.image_input_data.os_info_tag }}
      is_default_os: ${{ matrix.image_input_data.os_info_tag == matrix.image_input_data.default_os }}
      should_add_latest_tag: ${{ matrix.image_input_data.os_info_tag == matrix.image_input_data.default_os && matrix.image_input_data.release_tag == needs.generate-inputs.outputs.latest_release }}
      test_file_path: tests/matlab-deps/${{ matrix.image_input_data.test_file_name }}
